"""empty message

Revision ID: 2b9496e83241
Revises: ff2ac987d023
Create Date: 2022-06-21 20:16:27.293574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b9496e83241'
down_revision = 'ff2ac987d023'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location_file', sa.Column('type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('location_file', 'type')
    # ### end Alembic commands ###
