"""empty message

Revision ID: 3d587113a8d1
Revises: 4f03e5eca0c8
Create Date: 2022-06-09 14:02:23.253076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d587113a8d1'
down_revision = '4f03e5eca0c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('checklist_item', 'trip_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('location_image', 'location_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('trip', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('trip_comment', 'trip_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('trip_comment', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('trip_like', 'trip_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('trip_like', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trip_like', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('trip_like', 'trip_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('trip_comment', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('trip_comment', 'trip_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('trip', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('location_image', 'location_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('checklist_item', 'trip_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
