"""empty message

Revision ID: 424e0f0f199c
Revises: 772a3c344f42
Create Date: 2022-05-23 09:00:25.001096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '424e0f0f199c'
down_revision = '772a3c344f42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip', sa.Column('user_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'trip', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trip', type_='foreignkey')
    op.drop_column('trip', 'user_id')
    # ### end Alembic commands ###
