"""empty message

Revision ID: 4d78706326a3
Revises: e4717246b92e
Create Date: 2022-06-20 14:30:53.127682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d78706326a3'
down_revision = 'e4717246b92e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
