"""empty message

Revision ID: 4f03e5eca0c8
Revises: bd123cac249c
Create Date: 2022-06-09 11:23:52.411245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f03e5eca0c8'
down_revision = 'bd123cac249c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('location', 'trip_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('location', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('location_trip_id_fkey', 'location', type_='foreignkey')
    op.create_foreign_key(None, 'location', 'trip', ['trip_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'location', type_='foreignkey')
    op.create_foreign_key('location_trip_id_fkey', 'location', 'trip', ['trip_id'], ['id'])
    op.alter_column('location', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('location', 'trip_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
