"""empty message

Revision ID: 4f57b44a4ca2
Revises: ed0d9cdffb88
Create Date: 2022-06-07 08:46:24.004914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f57b44a4ca2'
down_revision = 'ed0d9cdffb88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip', sa.Column('can_be_reminded', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trip', 'can_be_reminded')
    # ### end Alembic commands ###
