"""empty message

Revision ID: 54850acaad12
Revises: 03e05ad6409a
Create Date: 2022-06-05 15:03:38.664348

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '54850acaad12'
down_revision = '03e05ad6409a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip', sa.Column('back_trip_at', sa.Date(), nullable=True))
    op.add_column('trip', sa.Column('is_finished', sa.Boolean(), nullable=True))
    op.drop_column('trip', 'finish_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip', sa.Column('finish_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('trip', 'is_finished')
    op.drop_column('trip', 'back_trip_at')
    # ### end Alembic commands ###
