"""empty message

Revision ID: 5f52b5020278
Revises: 13f704b274bb
Create Date: 2022-06-21 20:13:51.842101

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5f52b5020278'
down_revision = '13f704b274bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('location_file', 'type',
               existing_type=postgresql.ENUM('IMAGE', 'VIDEO', 'COMPRESS', name='filetype'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('location_file', 'type',
               existing_type=postgresql.ENUM('IMAGE', 'VIDEO', 'COMPRESS', name='filetype'),
               nullable=True)
    # ### end Alembic commands ###
