"""empty message

Revision ID: 6c990afeb6ee
Revises: dc1908415ce4
Create Date: 2022-05-30 22:15:36.377364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c990afeb6ee'
down_revision = 'dc1908415ce4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('user_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'location', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'location', type_='foreignkey')
    op.drop_column('location', 'user_id')
    # ### end Alembic commands ###
