"""Add comment_likes model

Revision ID: 7f4bcb49f889
Revises: 4d78706326a3
Create Date: 2022-06-20 15:29:45.243128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f4bcb49f889'
down_revision = '4d78706326a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
