"""empty message

Revision ID: 91a7133b0f31
Revises: 4de09cbf4cda
Create Date: 2022-06-19 09:55:11.627209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91a7133b0f31'
down_revision = '4de09cbf4cda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
