"""empty message

Revision ID: a20509493cee
Revises: 4f57b44a4ca2
Create Date: 2022-06-09 11:15:41.827725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a20509493cee'
down_revision = '4f57b44a4ca2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
