"""empty message

Revision ID: bd123cac249c
Revises: 2db389b37381
Create Date: 2022-06-09 11:18:08.682689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd123cac249c'
down_revision = '2db389b37381'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('location_trip_id_fkey', 'location', type_='foreignkey')
    op.create_foreign_key(None, 'location', 'trip', ['trip_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'location', type_='foreignkey')
    op.create_foreign_key('location_trip_id_fkey', 'location', 'trip', ['trip_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
