"""empty message

Revision ID: d15506249b29
Revises: 91a7133b0f31
Create Date: 2022-06-19 11:14:32.876938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd15506249b29'
down_revision = '91a7133b0f31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
