"""empty message

Revision ID: e15ae67c04ed
Revises: 424e0f0f199c
Create Date: 2022-05-29 21:53:58.870691

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e15ae67c04ed'
down_revision = '424e0f0f199c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip', sa.Column('start_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('trip', sa.Column('finish_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('trip', 'departure_at')
    op.drop_column('trip', 'day_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip', sa.Column('day_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('trip', sa.Column('departure_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('trip', 'finish_at')
    op.drop_column('trip', 'start_at')
    # ### end Alembic commands ###
