"""empty message

Revision ID: ed0d9cdffb88
Revises: 54850acaad12
Create Date: 2022-06-07 08:06:16.101110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed0d9cdffb88'
down_revision = '54850acaad12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trip', 'created_at')
    # ### end Alembic commands ###
