"""empty message

Revision ID: ff2ac987d023
Revises: 5f52b5020278
Create Date: 2022-06-21 20:16:02.273636

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ff2ac987d023'
down_revision = '5f52b5020278'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('location_file', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location_file', sa.Column('type', postgresql.ENUM('IMAGE', 'VIDEO', 'COMPRESS', name='filetype'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
